### ISSUE TITLE
Minimum Path Sum

### ISSUE THREAD

**Issue by Tanuj2552** [ritikkanotra/CompetitiveCoding#19]
I would like to add my code to the given [question](https://leetcode.com/problems/minimum-path-sum/) . please add the hacktoberfest label for it and assign it to me. 
Thank you[](url)

**Comment by ritikkanotra** [comment]
Hi Tanuj, please add your code now. Thanks for choosing this repository.
Also, I would like to connect with you on LinkedIn.
Till then, keep the josh high ;)

**Comment by Tanuj2552** [comment]
Yeah sure, no problem. I have added PR #24 to solve this. 
btw, my LinkedIn is https://www.linkedin.com/in/tanuj-t-v-s-b761651b1/

**Comment by ritikkanotra** [comment]
Yup, already sent you a request.
